language: php

os: linux
dist: xenial

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm

jobs:
  include:
    - php: 7.3
      env: MOODLE_BRANCH=master    DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist --repository=https://github.com/andrewnicols/moodle-plugin-ci moodlehq/moodle-plugin-ci ci gruntcli_45
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install --no-init

script:
  - moodle-plugin-ci grunt
